pipeline:

  build_any_branch:
    image: node:9
    commands:
      - npm i
      - npm run build --production

  scp:
    image: appleboy/drone-scp
    host: 104.211.187.39
    user: fluidex
    secrets: [ ssh_key ]
    target: /home/fluidex
    source: docs
    commands:
      - echo "Cool this seems to work"
    when:
        event: deployment
