pipeline:

  build_any_branch:
    image: node:9
    commands:
      - npm i
      - npm run build --production
      - tar -czvf bundle.tar.gz docs
      - ls

  scp:
    image: appleboy/drone-scp
    username: fluidex
    password: "2-tJ*0(*Wah|Qb<DpT7P,r`01NpQ#Mv[;kCXiYcw;p+J~-_e10ZTy*x>>W^O}pz"
    host: frontend.fluidex.global
    target: /home/fluidex
    source: bundle.tar.gz
    rm: true
    when:
        event: deployment
