pipeline:

  build_any_branch:
    image: node:9
    commands:
      - npm i --quiet
      - npm run build --production

  deploy_to_development:
    image: ispern/ubuntu-rsync-sshpass
    secrets: [ ssh_key ]
    commands:
      - sshpass -p "$SSH_KEY" rsync -avz -e 'ssh -o StrictHostKeyChecking=no' docs fluidex@frontend.fluidex.global:/home/fluidex --delete
    when:
      status: success 
      branch:
        include: master

