pipeline:

  build_any_branch:
    image: node:9
    commands:
      - npm i
      - npm run build --production
  when:
        event: deployment

  scp:
    image: appleboy/drone-scp
    secrets: [ ssh_username , ssh_key ]
    host: frontend.fluidex.global
    target: /home/fluidex
    source: docs
    rm: true
    when:
        event: deployment
